Update build_deploy.yml

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -39,10 +39,26 @@ jobs:
       run: |
         pelican content
 
-    - name: Deploy to GitHub Pages
+    - name: Fix permissions
+      run: |
+        chmod -c -R +rX "." | while read line; do
+          echo "::warning title=Invalid file permissions automatically fixed::$line"
+        done
+
+    - name: Copy output to root directory
+      run: |
+        mv -v output/* .
+        rm -rf output/* || true
+        rm -rf .[^.]* || true
+        rm -rf *
+        
+    - name: Upload Artifacts
+      uses: actions/upload-pages-artifact@v2
+      with:
+        path: .
+
+    - name: Deploy to CPACS website
       id: deployment
       uses: actions/deploy-pages@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
-        branch: gh-pages
-        folder: output
